// Generated by https://quicktype.io

export interface PackagesListRes {
  objects: packageObj[];
  total: number;
  time: string;
}

export interface packageObj {
  package: Package;
  score: Score;
  searchScore: number;
  flags?: Flags;
  backgroundColor?: string;
}

export interface Flags {
  unstable: boolean;
}

export interface Package {
  name: string;
  scope: string;
  version: string;
  description: string;
  keywords: string[];
  date: string;
  links: Links;
  author: Author;
  publisher: Publisher;
  maintainers: Publisher[];
}

export interface Author {
  name: string;
  email?: string;
  url?: string;
  username?: string;
}

// export enum Email {
//   AkashPatelMindinventoryCOM = 'akash.patel@mindinventory.com',
//   AnkitPrajapatiMindinventoryCOM = 'ankit.prajapati@mindinventory.com',
//   ChiragRamiMindinventoryCOM = 'chirag.rami@mindinventory.com',
//   PratikPatelMindinventoryCOM = 'pratik.patel@mindinventory.com',
//   PremshankarShahMindinventoryCOM = 'premshankar.shah@mindinventory.com',
//   RuturajJadejaMindinventoryCOM = 'ruturaj.jadeja@mindinventory.com',
//   TusharSanchaniyaMindinventoryCOM = 'tushar.sanchaniya@mindinventory.com',
// }

// export enum Username {
//   AkashPatelMi = 'akash.patel.mi',
//   AnkitPrajapati = 'ankit_prajapati',
//   ChiragMi = 'chirag.mi',
//   Pratikmi001 = 'pratikmi001',
//   PremshankarShah = 'premshankar_shah',
//   RuturajJadejaMi = 'ruturaj.jadeja.mi',
//   Tusharsanchaniya = 'tusharsanchaniya',
// }

export interface Links {
  npm: string;
  homepage: string;
  repository: string;
  bugs: string;
}

export interface Publisher {
  username: string;
  email: string;
}

export interface Score {
  final: number;
  detail: Detail;
}

export interface Detail {
  quality: number;
  popularity: number;
  maintenance: number;
}
