name: Publishing new boilerplate version on NPM.

on:
  push:
    tags:
      - "*"
jobs:
  build:
    if: github.ref == 'refs/heads/feat/CI-CD' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: dsstep-1
        run: echo "::called on create tag::"
